# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahorro',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='tipomovimiento',
            name='taza',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='tipo_ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiero.TipoMovimiento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiero.TipoMovimiento'),
        ),
        migrations.DeleteModel(
            name='TipoAhorro',
        ),
        migrations.DeleteModel(
            name='TipoPrestamo',
        ),
    ]
